eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8806
spring:
  application:
    name: zuul
zuul:
  routes:
    feign-url:
      path: /feign/**
      service-id: feign-consumer
    hystrix-url:
      path: /hystrix/**
      service-id: feign-hystrix-consumer

